name: FetchWBProjects

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'             
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Main script 
        run: python src/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
